config/routes.rb
BarApp::Application.routes.draw do
  get "static_pages/about"
  get "static_pages/home"

  resources :songs
  resources :bids
  
  match 'auth/:provider/callback', to: 'UserSessions#create'
  match 'auth/failure', to: redirect('/')  
    
  resources :jukeboxes
  resources :jukebox_songs
  resources :favorites
  
  match "/search_for_songs" => "JukeboxSongs#search_for_songs"
  match "/upvote" => "JukeboxSongs#upvote"
  match "/downvote" => "JukeboxSongs#downvote"
  match "/add_song_to_jukebox" => "Jukeboxes#add_song_to_jukebox"
  match "/get_playlist" => "Jukeboxes#get_playlist"
  match "/next_song" => "Jukeboxes#next_song"
  match "/set_current_song" => "Jukeboxes#set_current_song"
    
  match '/about' => "static_pages#about"
  
  resources :users
  
  resources :user_sessions
  
  root :to => "user_sessions#new"
  
  match "/login" => "user_sessions#new"
  match "/logout" => "user_sessions#destroy"
  match "/register" => "users#new"
  
  

end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :jukebox
  attr_accessible :amount, :song_artist, :song_name
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  filter_resource_access
  # GET /bids
  # GET /bids.json
  def index
    @bids = Bid.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bids }
    end
  end

  # GET /bids/1
  # GET /bids/1.json
  def show
    @bid = Bid.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bid }
    end
  end

  # GET /bids/new
  # GET /bids/new.json
  def new
    @bid = Bid.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bid }
    end
  end

  # GET /bids/1/edit
  def edit
    @bid = Bid.find(params[:id])
  end

  # POST /bids
  # POST /bids.json
  def create
    @bid = Bid.new(params[:bid])

    respond_to do |format|
      if @bid.save
        format.html { redirect_to @bid, notice: 'Bid was successfully created.' }
        format.json { render json: @bid, status: :created, location: @bid }
      else
        format.html { render action: "new" }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bids/1
  # PUT /bids/1.json
  def update
    @bid = Bid.find(params[:id])

    respond_to do |format|
      if @bid.update_attributes(params[:bid])
        format.html { redirect_to @bid, notice: 'Bid was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bids/1
  # DELETE /bids/1.json
  def destroy
    @bid = Bid.find(params[:id])
    @bid.destroy

    respond_to do |format|
      format.html { redirect_to bids_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/_form.html.erb
<%= form_for(@bid) do |f| %>
  <% if @bid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bid.errors.count, "error") %> prohibited this bid from being saved:</h2>

      <ul>
      <% @bid.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :bar %><br />
    <%= f.text_field :bar %>
  </div>
  <div class="field">
    <%= f.label :song_name %><br />
    <%= f.text_field :song_name %>
  </div>
  <div class="field">
    <%= f.label :song_artist %><br />
    <%= f.text_field :song_artist %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bids/edit.html.erb
<h1>Editing bid</h1>

<%= render 'form' %>

<%= link_to 'Show', @bid %> |
<%= link_to 'Back', bids_path %>

app/views/bids/index.html.erb
<h1>Listing bids</h1>

<table>
  <tr>
    <th>Amount</th>
    <th>User</th>
    <th>Bar</th>
    <th>Song name</th>
    <th>Song artist</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bids.each do |bid| %>
  <tr>
    <td><%= bid.amount %></td>
    <td><%= bid.user %></td>
    <td><%= bid.bar %></td>
    <td><%= bid.song_name %></td>
    <td><%= bid.song_artist %></td>
    <td><%= link_to 'Show', bid %></td>
    <td><%= link_to 'Edit', edit_bid_path(bid) %></td>
    <td><%= link_to 'Destroy', bid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bid', new_bid_path %>

app/views/bids/new.html.erb
<h1>New bid</h1>

<%= render 'form' %>

<%= link_to 'Back', bids_path %>

app/views/bids/show.html.erb
<p>
  <b>Amount:</b>
  <%= @bid.amount %>
</p>

<p>
  <b>User:</b>
  <%= @bid.user %>
</p>

<p>
  <b>Bar:</b>
  <%= @bid.bar %>
</p>

<p>
  <b>Song name:</b>
  <%= @bid.song_name %>
</p>

<p>
  <b>Song artist:</b>
  <%= @bid.song_artist %>
</p>


<%= link_to 'Edit', edit_bid_path(@bid) %> |
<%= link_to 'Back', bids_path %>