config/routes.rb
BarApp::Application.routes.draw do
  get "static_pages/about"
  get "static_pages/home"

  resources :songs
  resources :bids
  
  match 'auth/:provider/callback', to: 'UserSessions#create'
  match 'auth/failure', to: redirect('/')  
    
  resources :jukeboxes
  resources :jukebox_songs
  resources :favorites
  
  match "/search_for_songs" => "JukeboxSongs#search_for_songs"
  match "/upvote" => "JukeboxSongs#upvote"
  match "/downvote" => "JukeboxSongs#downvote"
  match "/add_song_to_jukebox" => "Jukeboxes#add_song_to_jukebox"
  match "/get_playlist" => "Jukeboxes#get_playlist"
  match "/next_song" => "Jukeboxes#next_song"
  match "/set_current_song" => "Jukeboxes#set_current_song"
    
  match '/about' => "static_pages#about"
  
  resources :users
  
  resources :user_sessions
  
  root :to => "user_sessions#new"
  
  match "/login" => "user_sessions#new"
  match "/logout" => "user_sessions#destroy"
  match "/register" => "users#new"
  
  

end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :artist, :name, :album, :url, :length
  has_many :jukebox_songs, :dependent => :destroy
  validates_uniqueness_of :name, :scope => [:artist], :message => "This song has already been submitted."
  before_save(:file_info)
    
  searchable do
    text :artist, :name, :album  
  end
  
  def file_info
    require 'taglib'
    
    # Load file from name
    TagLib::FileRef.open("public/tunes/" + self.name + ".mp3") do |fileref|
      unless fileref.null?
        song_info = tag = fileref.tag
        tag.title   #=> "Wake Up"
        tag.artist  #=> "Arcade Fire"
        tag.album   #=> "Funeral"
        tag.year    #=> 2004
        tag.track   #=> 7
        tag.genre   #=> "Indie Rock"
        tag.comment #=> nil

        properties = fileref.audio_properties
        properties.length  #=> 335 (song length in seconds)
        self.length = properties.length
        
      end
    end  # File is automatically closed at block end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  filter_resource_access
  
  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end
  
  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])
    @msg = get_flash

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end
  
  def get_flash
    msg = session[:msg]
    reset_session
    return msg
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    
    @song = Song.new
    session[:msg] = "smelly"
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(params[:song])
    
    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end
end

app/views/songs/_form.html.erb
<%= render "layouts/error_messages", :target => @song %>

<%= form_for(@song) do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :album %><br />
    <%= f.text_field :album %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table>
  <tr>
    <th>Song title</th>
    <th>Artist</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @songs.each do |song| %>
  <tr>
    <td><%= song.name %></td>
    <td><%= song.artist %></td>
    <td><%= song.url %></td>
    <td><%= link_to 'Show', song %></td>
    <td><%= link_to 'Edit', edit_song_path(song) %></td>
    <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vote', new_song_path %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p>
	<%= @msg if @msg %>
  <b>Song title:</b>
  <%= @song.name %>
</p>

<p>
  <b>Artist:</b>
  <%= @song.artist %>
</p>

<p>
  <b>Url:</b>
  <%= @song.url %>
</p>


<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>