config/routes.rb
BarApp::Application.routes.draw do
  get "static_pages/about"
  get "static_pages/home"

  resources :songs
  resources :bids
  
  match 'auth/:provider/callback', to: 'UserSessions#create'
  match 'auth/failure', to: redirect('/')  
    
  resources :jukeboxes
  resources :jukebox_songs
  resources :favorites
  
  match "/search_for_songs" => "JukeboxSongs#search_for_songs"
  match "/upvote" => "JukeboxSongs#upvote"
  match "/downvote" => "JukeboxSongs#downvote"
  match "/add_song_to_jukebox" => "Jukeboxes#add_song_to_jukebox"
  match "/get_playlist" => "Jukeboxes#get_playlist"
  match "/next_song" => "Jukeboxes#next_song"
  match "/set_current_song" => "Jukeboxes#set_current_song"
    
  match '/about' => "static_pages#about"
  
  resources :users
  
  resources :user_sessions
  
  root :to => "user_sessions#new"
  
  match "/login" => "user_sessions#new"
  match "/logout" => "user_sessions#destroy"
  match "/register" => "users#new"
  
  

end

app/models/jukebox.rb
class Jukebox < ActiveRecord::Base
  attr_accessible :city, :closing, :country, :latitude, :longitude, :name, :opening, :state, :street, :url
  has_many :favorites, :dependent => :destroy
  has_many :bids, :dependent => :destroy
  has_many :jukebox_songs, :dependent => :destroy
  has_many :votes, :dependent => :destroy
  belongs_to :user
  scope :not_user_jukeboxes, lambda { 
    |user| 
    arel = Jukebox.arel_table
    where(arel[:user_id].not_eq(user.id)) 
  }
  scope :user_jukeboxes, lambda { |user| where(:user_id => user.id) }
  validates_format_of :name, :with => /[a-z][1-9]$/, :message => " must only contain letters or numbers"
  validates_presence_of :name
  validates_uniqueness_of :name
  
  def set_current_song!
    jukebox_song = current_song
    
    # if current_song is not set, set it
    if jukebox_song.nil?
      
      # if a jukebox_song with rank 0 is not found, 
      # the playlist has not been ranked and needs to do so
      if jukebox_songs.find_by_rank(0).nil?
        rank!
      end
      
      jukebox_song = jukebox_songs.find_by_rank(0)

      jukebox_song.playing = true
      jukebox_song.save
    end
    
    return jukebox_song
    
  end
  
  def current_song
    
    # look for jukebox_songs that are playing
    jukebox_song ||= jukebox_songs.find_by_playing(true)
  end
  
  def current_song_set?
    return !jukebox_songs.find_by_playing(true).nil?
  end
  
  def empty_playlist?
    return jukebox_songs.empty?
  end
  
  # rank ranks all songs in the playlist based on votes submitted
  # rank is called after a song finishes playing, when a jukebox_song is added, 
  # a jukebox_song is deleted, when a vote is added, a vote is deleted
  def rank!
    
    # keep an array of arrays of size 2, with index 0 being 
    # the jukebox_song_id, index 1 being the number of votes for that jukebox_song
    vote_counts = []
    
    jukebox_songs.each do |jukebox_song|
      vote_counts.push([jukebox_song, jukebox_song.votes_count])
    end

    # sort the array by vote count
    vote_counts.sort_by! { |arr|
      arr[1]
    }.reverse!
            
    # assign rankings
    # if rankings have already been assigned to jukebox songs of this jukebox with jukebox_id,
    # skip jukebox_song with ranking of 0 because that's the currently playing jukebox_song
    vote_counts.each_with_index do |arr,i|
      jukebox_song = arr[0]
      
      # start with 0, rank 0 is current song playing
      jukebox_song.rank = i
      
      jukebox_song.save
    end
  end
end

app/controllers/jukeboxes_controller.rb
class JukeboxesController < ApplicationController
  filter_resource_access
  respond_to :xml, :html, :json
  caches_action :index, :cache_path => :cache_path.to_proc  

  def index
    if current_user
      @not_user_jukeboxes = Jukebox.not_user_jukeboxes(current_user)
      @user_jukeboxes = Jukebox.user_jukeboxes(current_user)
      @faved_jukeboxes = current_user.favorites.map! { |fave| fave.jukebox }
      respond_with(@jukeboxes)
    end
  end

  # GET /jukeboxs/1
  # GET /jukeboxs/1.json
  def show
    @jukebox = Jukebox.find(params[:id])
    @favorite = Favorite.where(:jukebox_id => params[:id]).find_by_user_id(current_user.id)
    @songs = @jukebox.jukebox_songs.order("rank ASC")
    
    respond_with(@jukebox)
  end

  # GET /jukeboxs/new
  # GET /jukeboxs/new.json
  def new
    @jukebox = Jukebox.new

    respond_with(@jukebox)
  end

  # GET /jukeboxs/1/edit
  def edit
    @jukebox = Jukebox.find(params[:id])
  end

  # POST /jukeboxs
  # POST /jukeboxs.json
  def create
    @jukebox = Jukebox.new(params[:jukebox])
    @jukebox.user_id = current_user.id

    respond_to do |format|
      if @jukebox.save
        format.html { redirect_to @jukebox, notice: 'Jukebox was successfully created.' }
        format.json { render json: @jukebox, status: :created, location: @jukebox }
      else
        format.html { render action: "new" }
        format.json { render json: @jukebox.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jukeboxs/1
  # PUT /jukeboxs/1.json
  def update
    @jukebox = Jukebox.find(params[:id])

    respond_to do |format|
      if @jukebox.update_attributes(params[:jukebox])
        format.html { redirect_to @jukebox, notice: 'Jukebox was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @jukebox.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jukeboxs/1
  # DELETE /jukeboxs/1.json
  def destroy
    @jukebox = Jukebox.find(params[:id])
    @jukebox.destroy

    respond_with(@jukebox)
  end
  
  def empty_playlist?
    @jukebox = Jukebox.find(params[:id])
    return @jukebox.empty_playlist?
  end
  
  def add_song_to_jukebox
    if current_user
      jukebox_song = JukeboxSong.new(params[:jukebox_song])
      jukebox_song.jukebox_id = params[:id]
      jukebox_song.user_id = current_user.id
      respond_to do |format|
        if jukebox_song.save
        
          jukebox = Jukebox.find(jukebox_song.jukebox_id)
        
          # rank jukebox's playlist
          jukebox.rank!
          
          # publish the new playlist to faye client
          publish_to_jukebox(jukebox.id)
          
          format.json { render json: { :success => "Song added to jukebox" } }
        else
          
          # failed validation -> song has already been submitted
          
          format.json { render json: "That song has already been submitted.", status: :unprocessable_entity }
        end
      end
    end
  end
  
  def get_playlist
    @songs = JukeboxSong.songs_for_jukebox(params[:id])
    render :partial => "playlist2", :locals => { :songs => @songs }
  end
  
  # when user clicks play or the track is at an end,
  # this function is called. It first sets current_song if
  # it is not set, which indicates the current song playing.
  def next_song
    
    # check if user is authorized to do this, REFACTOR    
    jukebox = Jukebox.find(params[:id])
    
    if user_authorized_for_object?(jukebox)
      
      if !jukebox.empty_playlist?
        # sets current song if it hasn't been set yet
        current_song = jukebox.set_current_song!
      
        if params[:type] == "next" # track is at its end

          # current_song playing is done playing, delete from db
          current_song.destroy
        
          # reload jukebox, REFACTOR!!!
          jukebox = Jukebox.find(params[:id])
    
        end      
        # check again if jukebox is empty
        if !jukebox.empty_playlist?
          # rerank the jukebox's playlist
          jukebox.rank!
      
          # set current_song based on new ranking
          jukebox.set_current_song!
        end
        
        # publish new playlist to faye client
        publish_to_jukebox(jukebox.id)
          
        # find newest current_song
        current_song = Jukebox.find(params[:id]).current_song
      
        respond_to do |format|
          if current_song
            format.json { render json: current_song.song }
          else
            format.json { render json: "Couldn't find another song!", status: :unprocessable_entity }
          end
        end
      end
    end   
  end
end

app/helpers/jukeboxes_helper.rb
module JukeboxesHelper
  
  def jukebox_title_div(jukebox, favorite)
    render :partial => "jukebox_title_div", :locals => { :jukebox => jukebox, :favorite => favorite }
  end
  
  def playlist(songs)
    render :partial => "playlist2", :locals => { :songs => songs}
  end
  
  def location(jukebox)
    if !jukebox.street.empty? && !jukebox.city.empty? && !jukebox.state.empty? && !jukebox.country.empty?
      content_tag(:div, "Located at " + jukebox.street + ", " + jukebox.city + "," + jukebox.state + "," + jukebox.country, :class => "location")
    end
  end
  
  def search_song(jukebox)
    @jukebox = jukebox
    if current_user
      render :partial => "search_song", :locals => { :jukebox => @jukebox }
    end
  end
  
  def jplayer(jukebox)
    if user_authorized_for_object?(jukebox) && !jukebox.empty_playlist?
      render :partial => "jplayer"
    end
  end
  
  def jukebox_chat
    if current_user
      render :partial => "chat"
    end
  end
end

app/views/jukeboxes/_chat.html.erb
<div class="chat_container">
  <h1> Talk to listeners </h1>
  <div class="chat_room" data-username="<%= current_user.username %>">
  </div>
 
  <form id="new_message_form">
    <input type="text" id="message" name="message">
    <input type="submit" value="Chat" class="btn btn-default">
  </form>
</div>

app/views/jukeboxes/_form.html.erb
<%= form_for(@jukebox) do |f| %>
  <% if @jukebox.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jukebox.errors.count, "error") %> prohibited this jukebox from being saved:</h2>

      <ul>
      <% @jukebox.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
	<br>
	<div class="field">
		<%= f.label :location %>
		<%= render :partial => "layouts/map" %>
	<br>
	</div>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :opening %><br />
    <%= f.time_select :opening %>
  </div>
  <div class="field">
    <%= f.label :closing %><br />
    <%= f.time_select :closing %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary"%>
  </div>
<% end %>

app/views/jukeboxes/_jplayer.html.erb
<div id="jp_container_1" class="jp-video jp-video-270p">
	<div class="jp-type-playlist">
		<div id="jquery_jplayer_1" class="jp-jplayer"></div>
		<div class="jp-gui">
			<div class="jp-interface">
				<div class="jp-progress">
					<div class="jp-seek-bar">
						<div class="jp-play-bar"></div>
					</div>
				</div>
				<div class="jp-current-time"></div>
				<div class="jp-duration"></div>
				<div class="jp-title">
					<div class="current_song">
						<h2> 
						</h2>
					</div>
				</div>
				<div class="jp-controls-holder">
					<ul class="jp-controls">
						<li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
						<li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
						<li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
						<li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
						<li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
						<li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
					</ul>
					<div class="jp-volume-bar">
						<div class="jp-volume-bar-value"></div>
					</div>
					<ul class="jp-toggles">
						<li><a href="javascript:;" class="jp-full-screen" tabindex="1" title="full screen">full screen</a></li>
						<li><a href="javascript:;" class="jp-restore-screen" tabindex="1" title="restore screen">restore screen</a></li>
						<li><a href="javascript:;" class="jp-shuffle" tabindex="1" title="shuffle">shuffle</a></li>
						<li><a href="javascript:;" class="jp-shuffle-off" tabindex="1" title="shuffle off">shuffle off</a></li>
						<li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
						<li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
					</ul>
				</div>
			</div>
		</div>
		<div class="jp-playlist">
			<ul>
				<!-- The method Playlist.displayPlaylist() uses this unordered list -->
				<li></li>
			</ul>
		</div>
		<div class="jp-no-solution">
			<span>Update Required</span>
			To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
		</div>
	</div>
</div>

app/views/jukeboxes/_jukebox_title_div.html.erb
<div class="title">
	<%= jukebox.name %>
	<br>
	<a href="#" id="favorite_<%= jukebox.id %>" data-fave-id="<%= favorite ? favorite.id : "" %>" class="<%= favorite ? "favorited" : "unfavorited" %>"><i class="icon-thumbs-up"></i></a>
</div>

app/views/jukeboxes/_playlist.html.erb
<ul class="songs">
<% songs.each do |song| %>
  <li class="song" id="<%= song.id %>">
	  <% if current_user %>
	    <a data-jukebox-song="<%= song.id %>" class="upvote_action"><i class="icon-arrow-up"></i></a>
	    <a data-jukebox-song="<%= song.id %>" class="downvote_action"><i class="icon-arrow-down"></i></a>
      <% end %>
	  <br>
    <% if song.rank %>
	  <%= song.rank %>. 
	<% end %>
	"<%= song.song_title %>" by <%= song.artist %> </h2>
    <div class="submitted_by">
  	  Submitted by <%= user_div(song.user) %> 
  	  <% if song.user.uid %>
  	    <img src="http://graph.facebook.com/<%= song.user.uid %>/picture?type=small" alt="profile pic">
  	  <% end %>
	  <br>
	  Votes: <div id="<%= song.id %>" class="jukebox_song_vote_count"> <%= song.votes_count %> </div>
	  <br>
    </div>
  </li>
<% end %>
</ul>

app/views/jukeboxes/_playlist2.html.erb
<h1> The Playlist </h1>	
<br>
<table class="playlist_table">
	<tr>
		  <% if current_user %>
			<th>  </th>
	      <% end %>
		<th>  </th>
		<th>  </th>
		<th>  </th>
		<th>  </th>
		<th>  </th>
	</tr>		
	<% songs.each do |song| %>
	<tr class="song" id="<%= song.id %>">
		  <td>
				<div class="ranking">
	  	  	<%= song.rank + 1 %>
				</div>
		  </td>
  		  <% if current_user %>
			    <td id="actions">
							<a data-jukebox-song="<%= song.id %>" class="upvote_action"><i class="icon-arrow-up"></i></a>
								<div id="<%= song.id %>" class="jukebox_song_vote_count">
				  	    	<%= song.votes_count %>
					    	</div>
		    			<a data-jukebox-song="<%= song.id %>" class="downvote_action"><i class="icon-arrow-down"></i></a>
			    </td>
	      <% end %>
		  <td>
			<h2>
				"<%= song.song_title %>"
			</h2>
		  </td>
		  <td>
			  <h2>
				  <%= song.artist %>
			  </h2>
		  </td>
	      <td>
		  	  <%= user_div(song.user) %> 
		  </td>
		  <td>
		  	  <% if song.user.uid %>
		  	    <img src="http://graph.facebook.com/<%= song.user.uid %>/picture?type=small" id="profile" alt="profile pic">
		  	  <% end %>
		  </td>
		  <td>
			  <% if user_authorized_for_object?(song)  %>
		        <%= link_to content_tag(:i,"",:class => "icon-trash"),"delete", :class => "delete_jukebox_song btn btn-default", :data => song.id %>
			  <% end %>
		  </td>
	  </tr>
	<% end %>
</table>

app/views/jukeboxes/_search_results.html.erb
<table>
  <% results.each do |r| %>
		<tr>
			<td>
			  <b> "<%= r.name %>" </b> by <%= r.artist %>
				<% if r.album %>
				  <i> from <b> <%= r.album %> </b> </i>
				<% end %>
			</td>
			<td>
				<%= content_tag(:a, "Add", :data => r.id, :class => "btn btn-default add_song_to_playlist") %>
			</td>
		</tr>
  <% end %>
</table>

app/views/jukeboxes/edit.html.erb
<h1>Editing Jukebox</h1>

<%= render 'form' %>

<%= link_to 'Show', @jukebox %> |
<%= link_to 'Back', jukeboxes_path %>

app/views/jukeboxes/index.html.erb
<%= content_for_block("jukeboxes", "map") %>

<div class="jukeboxes_index">
	<h1> Find Your Jukebox </h1>
	
	<%= form_tag '/search', :method => 'put' do %>
	<label for='search'> Search </label>
	<%= text_field_tag 'search' %>
	<% end %>
	<br>
	
	<% if !@user_jukeboxes.empty? %>
		<h1> My Jukeboxes </h1>
		<ul>
		<%= cache @user_jukeboxes do %>
				<% @user_jukeboxes.each do |juke| %>
				<li><%= link_to juke.name, jukebox_path(juke.id) %></li>
			<% end %>
			<hr>
		<% end %>
		</ul>			
	<% end %>
	<% if !@faved_jukeboxes.empty? %>
		<h1> My favorited Jukeboxes </h1>
		<ul>
		<% @faved_jukeboxes.each do |juke| %>
			<br>
			<li><%= link_to juke.name, jukebox_path(juke.id) %> </li>
			<% end %>
		</ul>
	<% end %>
	<h1> Other Jukeboxes </h1>
	<ul>	
		<% @not_user_jukeboxes.each do |juke| %>
		<li>
			<%= link_to juke.name, jukebox_path(juke.id) %> 
		</li>
	<% end %>
</ul>
	<hr>
	<i class="icon-level-up"></i> <%= link_to "Create a jukebox", new_jukebox_path, :class => "btn btn-default" %>
</div>

app/views/jukeboxes/new.html.erb
<% content_for_block("map") %>

<h1>New Jukebox</h1>

<%= render 'form' %>

<%= link_to 'Back', jukeboxes_path, :class => "btn btn-default" %>

app/views/jukeboxes/show.html.erb
<%= content_for_block("show_jukebox","jplayer_process") %>

<input type="hidden" class="user_id" data-user-id="<%= current_user.id %>" />
<div class="jukebox_header" id="<%= @jukebox.id %>">
	<%= jukebox_title_div(@jukebox, @favorite) %>

<div class="jquery_jplayer">
	
</div>

<%= jplayer(@jukebox) %>
<%= location(@jukebox) %>

<div class="middle">
	<div class="playlist">
		<h1> The Playlist </h1>	
		<br>
		<div class="playlist_table">
			<%= playlist(@songs) %>
		</div>
	</div>
	<br>
	<%= search_song(@jukebox) %>
</div>

<%= jukebox_chat %>

<p>
  <b>Opening time:</b>
  <%= @jukebox.opening %>
  
  <b>Closing time:</b>
  <%= @jukebox.closing %>
</p>

<div class="bottom">
	<%= object_links_bottom(@jukebox) %>
</div>